name: Bug report
description: Report a reproducible bug in ALBIS
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail for someone else to reproduce it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short bug description
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, including files and settings when relevant
      placeholder: |
        1. Open ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: ALBIS version / commit
      placeholder: e.g. v0.7, commit abc1234
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS and version
      placeholder: e.g. macOS 15.3 / Ubuntu 22.04 / Windows 11
    validations:
      required: true
  - type: dropdown
    id: install-mode
    attributes:
      label: Install / run mode
      options:
        - Python source run
        - Standalone package
        - Unknown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant backend/frontend logs and add screenshots if helpful
      render: shell
