export function createRoiState() {
  return {
    // Active ROI geometry and derived plot configuration.
    mode: "none",
    start: null,
    end: null,
    active: false,
    log: false,
    stats: null,
    lineProfile: null,
    xProjection: null,
    yProjection: null,
    innerRadius: 0,
    outerRadius: 0,
    plotLimits: {
      autoscale: true,
      line: { xMin: null, xMax: null, yMin: null, yMax: null },
      x: { xMin: null, xMax: null, yMin: null, yMax: null },
      y: { xMin: null, xMax: null, yMin: null, yMax: null },
    },
  };
}

export function createAnalysisState() {
  return {
    // Analysis overlays rendered on top of the current frame.
    ringsEnabled: false,
    distanceMm: null,
    pixelSizeUm: null,
    energyEv: null,
    centerX: null,
    centerY: null,
    rings: [1, 2, 4, 8],
    ringCount: 3,
    peaksEnabled: false,
    peakCount: 25,
    peaks: [],
    externalPeakSets: [],
    selectedPeaks: [],
    peakSelectionAnchor: null,
  };
}

export function createAppState() {
  return {
    // Global view/data state used across renderer + UI controls.
    file: "",
    dataset: "",
    shape: [],
    dtype: "",
    frameCount: 1,
    frameIndex: 0,
    thresholdCount: 1,
    thresholdIndex: 0,
    thresholdEnergies: [],
    seriesFiles: [],
    seriesLabel: "",
    imageHeaderFile: "",
    imageHeaderText: "",
    backendAlive: false,
    backendVersion: "0.5",
    toolHintsEnabled: false,
    pixelLabelMinCellPx: 18,
    pixelLabelMaxLabels: 4000,
    pixelLabelFormat: "auto",
    pixelLabelShowDuringDrag: false,
    isLoading: false,
    pendingFrame: null,
    playing: false,
    playTimer: null,
    fps: 1,
    step: 1,
    panelWidth: 640,
    panelCollapsed: true,
    autoScale: true,
    min: 0,
    max: 1,
    colormap: "albulaHdr",
    invert: false,
    zoom: 1,
    renderOffsetX: 0,
    renderOffsetY: 0,
    panOffsetX: 0,
    panOffsetY: 0,
    dataRaw: null,
    dataFloat: null,
    histogram: null,
    stats: null,
    histLogX: true,
    histLogY: true,
    pixelLabels: true,
    maskRaw: null,
    maskShape: null,
    maskAvailable: false,
    maskEnabled: false,
    maskSaturatedEnabled: false,
    maskAuto: true,
    maskFile: "",
    maskPath: "",
    hasFrame: false,
    width: 0,
    height: 0,
    globalStats: null,
    autoload: {
      mode: "file",
      watchEnabled: false,
      dir: "",
      interval: 1000,
      types: {
        hdf5: true,
        tiff: true,
        cbf: true,
        edf: true,
      },
      pattern: "",
      simplonUrl: "",
      simplonVersion: "1.8.0",
      simplonTimeout: 500,
      simplonEnable: true,
      remoteSourceId: "default",
      remoteSeq: 0,
      remoteMeta: {},
      autoStart: false,
      running: false,
      timer: null,
      busy: false,
      lastFile: "",
      lastMtime: 0,
      lastUpdate: 0,
      lastPoll: 0,
      lastMonitorSig: "",
      lastRemoteSeq: 0,
      lastMaskAttempt: 0,
      simplonMeta: {},
    },
    seriesSum: {
      running: false,
      jobId: "",
      progress: 0,
      message: "Idle",
      outputs: [],
      openTarget: "",
      autoOutputPath: "",
    },
  };
}
